### ISSUE TITLE
netpoll dose not support SetReadDeadline

### ISSUE THREAD

**Issue by FlameMida** [hertz-contrib/websocket#10]
**Describe the bug**
in the example chat
```go
c.Conn.SetReadDeadline(time.Now().Add(pongWait))
```
this function return this error 

**Screenshots**

![image](https://user-images.githubusercontent.com/33086993/205602645-11d19753-052f-4849-a0fd-2b33e5230bd8.png)

**Hertz version:**

0.4.1

**Comment by FlameMida** [comment]
by the way ,when i use 
```go 
c.Conn.WriteControl(websocket.PingMessage, nil, time.Now().Add(pongWait))
```
 in writePump.then will return an error in 

```go
c.Conn.ReadMessage()
```
 netpoll dose not support SetReadDeadline

![image](https://user-images.githubusercontent.com/33086993/205609920-d696e708-93d2-4fcc-96e5-9086658a36f2.png)

**Comment by li-jin-gou** [comment]
SetReadDeadline() and other Deadline-related interfaces are not implemented, so if you have a similar need to set a timeout you can.
```
err := upgrader.Upgrade(ctx, func(ws *websocket.Conn) {
   defer ws.Close()
  
   // "github.com/cloudwego/hertz/pkg/network"
   ws.UnderlyingConn().(network.Conn).SetReadTimeout(1 * time.Second)
   ....
}
```
we will add it to webscokect doc cc @BaiZe1998

**Comment by FlameMida** [comment]
> SetReadDeadline() and other Deadline-related interfaces are not implemented, so if you have a similar need to set a timeout you can.
> 
> ```
> err := upgrader.Upgrade(ctx, func(ws *websocket.Conn) {
>    defer ws.Close()
>   
>    // "github.com/cloudwego/hertz/pkg/network"
>    ws.UnderlyingConn().(network.Conn).SetReadTimeout(1 * time.Second)
>    ....
> }
> ```
> 
> we will add it to webscokect doc cc @BaiZe1998

ok,i will try it.thx
