### ISSUE TITLE
the lack of client code

### ISSUE THREAD

**Issue by cqqqq777** [hertz-contrib/websocket#14]
当我使用```hertz-contrib/websocket```时发现缺少了一些**客户端**的方法，类似```gorilla/websocket```中的Dial方法：https://github.com/gorilla/websocket/blob/master/client.go#L116
![image](https://user-images.githubusercontent.com/115757192/224682199-221780df-ecc9-410d-9415-90a9c5248353.png)

希望在以后的维护中可以加入有关**客户端**的方法

**Comment by welkeyever** [comment]
Currently, we may not have enough time to put into this. 
I will put the `good first issue` tag for it first.
If you are interested in it, any PR is welcome.

**Comment by shivamganwani** [comment]
@welkeyever I am new to open source and I had to translate what @cqqqq777 said.
So just to confirm that I have understood correctly. 
We need to add missing client methods in hertz-contrib/websocket, and I can refer to gorilla/websocket. One of them in Dial but we might need others as well.
Please tell me if there is anything else in the req.

**Comment by welkeyever** [comment]
@shivamganwani Sorry for the late, I just came back from vacation.
Yes, it is open to do so like your said - mostly the dial and related APIs - regarding gorilla/websocket.
Let me know if you are interested in it, and I will assign it to you🫡

**Comment by qleein** [comment]
@welkeyever I want to patch hertz/contrib/websocket to support websocket client，based on hertz client，but found it is difficult.  because the hertz client do not provide any function to access current connection after response 101 and switch protocol to websocket.   what i can do is reading body streamly.   Is there any suggestion？

**Comment by welkeyever** [comment]
@qleein Good point! It seems like we need to open a door for client to hijack the connection. If you are interested in the follow-up and task dismantling, you may lit up an issue [here](https://github.com/cloudwego/hertz/issues), and do it. Or I will come back later and take a closer look after the things at hand are over.

**Comment by xiaost** [comment]
Fixed in #24 , check test for example.
