### ISSUE TITLE
线程的阻塞问题

### ISSUE THREAD

**Issue by cqqqq777** [hertz-contrib/websocket#15]
在升级websocket服务的函数中
![image](https://user-images.githubusercontent.com/115757192/224735636-68b7dcce-6aa1-4b6f-997d-4a1ed5aa353e.png)
![image](https://user-images.githubusercontent.com/115757192/224735697-8c556acb-b409-4af5-a46d-6045adb14460.png)

Upgrade方法中的函数不会自动阻塞，如果此时有客户端来连接，因为不会阻塞，函数执行完毕后连接直接关了，这里
开启的协程也会报空指针错误
![image](https://user-images.githubusercontent.com/115757192/224737926-5978858c-91f5-4fa5-996f-f7199b71f23d.png)

如果在Upgrade方法中的函数里面添加阻塞函数的代码，就能正常运行
![image](https://user-images.githubusercontent.com/115757192/224738218-b6e95ca8-637e-4fb6-a7d0-7cfa5e4b6201.png)

但是websocket是一个长连接，我认为应该由websocket包来阻塞这里的进程，而不是让用户自行阻塞

我在使用gorilla的websocket库时，就没有这样的情况发生

**Comment by Nihilism0** [comment]
1.空指针问题：这样使用不会报空指针，因为Upgrade方法后面可以直接跟Handler自动传入conn
<img width="679" alt="image" src="https://user-images.githubusercontent.com/114405451/224871159-e91da2f6-966a-4874-a89c-7459df47327e.png">
2.由于websocket需要接受信息，则需要进行绑定结构体，在绑定的时候便会阻塞
<img width="530" alt="image" src="https://user-images.githubusercontent.com/114405451/224872218-791401a9-73a2-4680-9258-3190f7499699.png">

**Comment by Nihilism0** [comment]
You do not need to use select to block. If there is only one Write function, you do not need to use goroutine
<img width="571" alt="image" src="https://user-images.githubusercontent.com/114405451/224889443-5d225272-b132-456d-bd08-22fff60e8081.png">
If there are two functions, you can use goroutine for the first and not for the second. This statement is based on chat example
<img width="552" alt="image" src="https://user-images.githubusercontent.com/114405451/224889361-f119b61e-c63e-42d2-8caf-1f3088b148c1.png">

**Comment by FGYFFFF** [comment]
可以参考 readme 来写一下，看起来可以进行循环读写
