### ISSUE TITLE
客户端用局域网链接不成功

### ISSUE THREAD

**Issue by chenke1115** [hertz-contrib/websocket#16]
![image](https://user-images.githubusercontent.com/45746058/225807789-2f1b866c-cdf8-424e-a7ae-691ed08ab5ee.png)
局域网链接不成功
![image](https://user-images.githubusercontent.com/45746058/225807830-39f859ab-e1e3-4b60-908e-ff18479d7011.png)
切换本地可以链接成功

**Comment by rogerogers** [comment]
可以看下你server端listen的配置，是不是只配置了localhost，局域网需要配置`0.0.0.0:8091`，或者`:8091`

**Comment by chenke1115** [comment]
> 端

肯定不会犯这种低级失误呀😂

**Comment by Duslia** [comment]
emmm 你可以 ping 一下，测试一下能不能通。

**Comment by chenke1115** [comment]
> emmm 这个跟框架关系不大吧，你可以 ping 一下，测试一下能不能通。

通的，API接口都可以正常访问，ws就是找不到啥原因链接不上，代码逻辑什么的没有改变，文档也找不到相关的配置参数会影响到的

**Comment by rogerogers** [comment]
用代码访问ws通吗，你这个网页我试了下感觉并不支持本地网络。

**Comment by chenke1115** [comment]
> 支持



> 

我自己链接是通的，目前是前端同事没办法链接上，感觉是跟这个工具一样的情况
<img width="1398" alt="image" src="https://user-images.githubusercontent.com/45746058/225826936-bd59f633-c4da-4748-96ab-a4598a52d257.png">

**Comment by rogerogers** [comment]
那这个肯定是网络原因了，跟框架没啥关系，`ping` or `nc` or `telnet`看下吧。
