### ISSUE TITLE
Close无效

### ISSUE THREAD

**Issue by eininst** [hertz-contrib/websocket#17]
upgrader.Upgrade(c, func(conn *websocket.Conn) {   
        err := conn.Close()
        if err != nil {
            return
        }
        err = conn.WriteJSON(utils.H{"name": "hello"})
        if err != nil {
            return
        }
    })

#服务端调用close 关闭连接后，客户端依然可以收到消息

**Comment by li-jin-gou** [comment]
I will investigate it

**Comment by welkeyever** [comment]
Set [this](https://github.com/cloudwego/hertz/blob/develop/pkg/route/engine.go#L148) to `true` if you need close the Conn manually. And set [this](https://github.com/cloudwego/hertz/blob/develop/pkg/route/engine.go#L141) to `true`, if it is difficult to guarantee that `hijackConn` will not be closed repeatedly.

Context goes here:https://github.com/cloudwego/hertz/blob/develop/pkg/route/engine.go#L393

**Comment by eininst** [comment]
> Set [this](https://github.com/cloudwego/hertz/blob/develop/pkg/route/engine.go#L148) to `true` if you need close the Conn manually. And set [this](https://github.com/cloudwego/hertz/blob/develop/pkg/route/engine.go#L141) to `true`, if it is difficult to guarantee that `hijackConn` will not be closed repeatedly.
> 
> Context goes here:https://github.com/cloudwego/hertz/blob/develop/pkg/route/engine.go#L393

谢谢， 可以了
设置 h.KeepHijackedConns = true  就可以成功关闭了

**Comment by li-jin-gou** [comment]
This issue has helped a few people and it's great.
