### ISSUE TITLE
感觉直接基于netpoll解析websocket协议会更好

### ISSUE THREAD

**Issue by lxzan** [hertz-contrib/websocket#18]

**Comment by welkeyever** [comment]
如果是能够利用当前的nocopy特性，是的。不过需要的一定的适配开发量，有兴趣可以试试。

**Comment by lxzan** [comment]
> 如果是能够利用当前的nocopy特性，是的。不过需要的一定的适配开发量，有兴趣可以试试。

还有个好处是可以节省协程, 现在的Upgrade API看起来是一个连接一个协程.

**Comment by welkeyever** [comment]
可以试试，如果采用netpoll触发，需要区分onData触发后执行websocket链接升级还是直接进入websocket解包

**Comment by lxzan** [comment]
我是在完成websocket握手后调用SetOnRequest, 已经通过所有Autobahn WebSocket Testsuite测试用例了, 不知道还有没有其他问题

**Comment by Duslia** [comment]
可以把 PR 提出来瞅瞅~

**Comment by lxzan** [comment]
> 

PR就免了吧, 会把本项目搞得面目全非, 而且我是基于[gws](https://github.com/lxzan/gws)改的. 思路很简单, 把基于http.Request的Upgrade改成从netpoll.Connection解析http header然后重新设置OnRequest就行了

**Comment by welkeyever** [comment]
如果成熟的话，可以搞个独立仓库放到hertz-contrib下面

**Comment by lxzan** [comment]
> 如果成熟的话，可以搞个独立仓库放到hertz-contrib下面

成熟不敢说, 缺乏生产使用的案例, Autobahn测试都通过了, 个人项目中使用也没发现有什么毛病. 如果单独开个项目, 我乐于贡献代码.

**Comment by Duslia** [comment]
可以提到这个仓库哈： https://github.com/hertz-contrib/websocket-netpoll

**Comment by lxzan** [comment]
> 可以提到这个仓库哈： https://github.com/hertz-contrib/websocket-netpoll

👌🏻

**Comment by lxzan** [comment]
autobahn testcase 1
-10都没问题, 但是卡在 12-13 了, 有时候会长时间pending, 我的使用方式有问题吗?
代码仓库: https://github.com/lxzan/websocket-netpoll

**Comment by welkeyever** [comment]
> autobahn testcase 1 -10都没问题, 但是卡在 12-13 了, 有时候会长时间pending, 我的使用方式有问题吗? 代码仓库: https://github.com/lxzan/websocket-netpoll

如果是和netpoll处理相关，可以直接在netpoll下面提个issue哈：https://github.com/cloudwego/netpoll/issues

**Comment by lxzan** [comment]
你们基于gorilla改的 github.com/hertz-contrib/websocket 有跑过autobahn 测试吗? 
下班之后我再验证下, 看看要不要提issue

**Comment by welkeyever** [comment]
gorilla这套autobahn应该是全过的
