### ISSUE TITLE
压测数据内存占用较高，请帮忙看下压测代码是否可以优化

### ISSUE THREAD

**Issue by lesismal** [hertz-contrib/websocket#19]
首先建议一下issue模板，不只是有 Bug 或者 Feature request 这两类的 issue，所以可以多添加点分类，或者条件更宽松一点的模板。

我在做一些 websocket 框架的压测，仓库在这里：
https://github.com/lesismal/go-websocket-benchmark

压测中发现，相比于其他框架， hertz-contrib/websocket 内存占用较高，比如某一轮测试数据对比：
![image](https://github.com/hertz-contrib/websocket/assets/40462947/e115d0a2-d152-4d86-93da-c73efa087704)

hertz 的代码在这里，不太清楚是不是哪里写的不对，请帮忙看一下，如果可以优化，欢迎 PR 修正一下：
https://github.com/lesismal/go-websocket-benchmark/blob/main/frameworks/hertz/server.go

**Comment by lesismal** [comment]
请问框架有默认的最大连接数限制吗？我压测的时候遇到建立连接卡在9999个，始终达不到1w连接，但是同一个客户端到其他框架都是可以正常建立大于1w的连接数的：
![image](https://github.com/hertz-contrib/websocket/assets/40462947/45c8c114-ab14-4557-9fc4-8ddbd4de7a0b)

**Comment by li-jin-gou** [comment]
@lesismal  netpoll 默认协程池 1w 大小，另外 netpoll 的触发模型和其它框架不一样导致内存占用高。

**Comment by li-jin-gou** [comment]
可以使用 server.New 初始化实例&&尝试切换到标准库试试

**Comment by lesismal** [comment]
> @lesismal netpoll 默认协程池 1w 大小，另外 netpoll 的触发模型和其它框架不一样导致内存占用高。

好的感谢！
使用netpoll仍然是每个连接固定占用一个协程？

**Comment by li-jin-gou** [comment]
这个是 hertz 会管理空闲链接，每个连接固定占用一个协程，可以设置关闭。
![image](https://github.com/hertz-contrib/websocket/assets/97824201/ce48f2f6-ba85-4565-a16d-1b6aaedf8549)

**Comment by lesismal** [comment]
> netpoll 的触发模型和其它框架不一样导致内存占用高

@li-jin-gou 
目前的压测 TPS 不如其他几个库好，但是内存占用高的多，这有点得不偿失了，ws毕竟不像kitex这种内部服务之间RPC调用连接数比较少，ws主要都是面向公网的服务、用户数量可能很大的。

**Comment by li-jin-gou** [comment]
> > netpoll 的触发模型和其它框架不一样导致内存占用高
> 
> @li-jin-gou 目前的压测 TPS 不如其他几个库好，但是内存占用高的多，这有点得不偿失了，ws毕竟不像kitex这种内部服务之间RPC调用连接数比较少，ws主要都是面向公网的服务、用户数量可能很大的。

切换到 标准库 和 server.new 试试

**Comment by lesismal** [comment]
> 切换到 标准库 和 server.new 试试

这个怎么切，在README和[examples](https://github.com/hertz-contrib/websocket/tree/main/examples)里没找到

**Comment by li-jin-gou** [comment]
https://github.com/lesismal/go-websocket-benchmark/blob/main/frameworks/hertz/server.go#L62
 
server.Default => server.New , server.Default  默认自带了一个中间件会存在影响。

**Comment by lesismal** [comment]
> https://github.com/lesismal/go-websocket-benchmark/blob/main/frameworks/hertz/server.go#L62
> 
> server.Default => server.New

好的，tks

**Comment by lesismal** [comment]
> server.Default => server.New

试了 server.New，建立连接还是卡在9999。。。

**Comment by li-jin-gou** [comment]
> > server.Default => server.New
> 
> 试了 server.New，建立连接还是卡在9999。。。

https://www.cloudwego.io/zh/docs/hertz/reference/config/ 

![image](https://github.com/hertz-contrib/websocket/assets/97824201/5658eba2-37ed-45bf-a978-31f16e4bfcc2)

![image](https://github.com/hertz-contrib/websocket/assets/97824201/df36cb89-4bbd-4432-a2a3-4e4e20bbe7da)


参考一下可以适当调大或切换到标准库

**Comment by lesismal** [comment]
> 参考一下可以适当调大或切换到标准库

切换到标准库的意思是指 不使用 hertz websocket ？

我之前理解还以为你是说用标准库的 http Server Upgrade 后由 hertz websocket 处理

**Comment by lesismal** [comment]
@li-jin-gou  修改了 gopool size 后可以正常测 1w 了，感谢答疑！

但是这个性能和占用确实还是有点跨，你们先记录上、以后优化吧，issue我先关闭俩。

|      Framework       | Conns | Payload |  Total  | Success | Failed | Used  | CPU Avg | MEM Avg |   Avg   |  TPS   |  TP50   |  TP90   |  TP99   |
|      ---             |  ---  |   ---   |   ---   |   ---   |  ---   |  ---  |   ---   |   ---   |   ---   |  ---   |   ---   |   ---   |   ---   |
|    fasthttp_ws       | 10000 |  1024   | 1000000 | 1000000 |   0    | 4.84s | 233.98% | 224.23M | 24.09ms | 206766 | 22.92ms | 39.60ms | 57.47ms |
|     gobwas           | 10000 |  1024   | 1000000 | 1000000 |   0    | 7.73s | 370.27% | 92.50M  | 38.55ms | 129301 | 37.37ms | 48.94ms | 83.57ms |
|     gorilla          | 10000 |  1024   | 1000000 | 1000000 |   0    | 4.86s | 232.82% | 224.30M | 24.23ms | 205704 | 23.04ms | 39.63ms | 62.32ms |
|      gws             | 10000 |  1024   | 1000000 | 1000000 |   0    | 4.88s | 225.42% | 149.99M | 24.31ms | 204810 | 23.19ms | 40.09ms | 59.55ms |
| gws_basedon_stdhttp  | 10000 |  1024   | 1000000 | 1000000 |   0    | 4.77s | 286.34% | 258.24M | 23.76ms | 209639 | 22.68ms | 37.91ms | 57.70ms |
|      hertz           | 10000 |  1024   | 1000000 | 1000000 |   0    | 6.41s | 274.98% | 476.42M | 31.92ms | 156062 | 29.78ms | 44.97ms | 57.49ms |
| nbio_basedon_stdhttp | 10000 |  1024   | 1000000 | 1000000 |   0    | 5.14s | 263.08% | 170.56M | 25.60ms | 194630 | 24.49ms | 41.05ms | 66.79ms |
|  nbio_mod_blocking   | 10000 |  1024   | 1000000 | 1000000 |   0    | 4.99s | 261.74% | 158.96M | 24.87ms | 200343 | 23.69ms | 40.40ms | 59.93ms |
|   nbio_mod_mixed     | 10000 |  1024   | 1000000 | 1000000 |   0    | 5.04s | 266.48% | 193.17M | 25.13ms | 198285 | 23.44ms | 41.53ms | 62.46ms |
| nbio_mod_nonblocking | 10000 |  1024   | 1000000 | 1000000 |   0    | 6.16s | 303.71% | 61.84M  | 30.69ms | 162253 | 29.82ms | 47.43ms | 67.33ms |
|     nhooyr           | 10000 |  1024   | 1000000 | 1000000 |   0    | 5.90s | 320.82% | 353.26M | 29.38ms | 169456 | 28.73ms | 38.29ms | 53.41ms |

**Comment by li-jin-gou** [comment]
https://www.cloudwego.io/zh/docs/hertz/tutorials/basic-feature/network-lib/#%E7%BD%91%E7%BB%9C%E5%BA%93%E9%80%89%E6%8B%A9 可以看下文档

**Comment by li-jin-gou** [comment]
websocket 场景使用 hertz 标准库模式就好了。

**Comment by lesismal** [comment]
> websocket 场景使用 hertz 标准库模式就好了。

因为是fork gorilla的，测试基于标准库意义不大，直接用gorilla就可以了。
主要想对比下基于netpoll的是否有性能提升带来质的提高。
但看上去性能并不比基于标准库强，内存占用却可能比java还吞金兽。
目前版本对比下来、没什么意义使用基于netpoll的，期待你们以后能优化得更好吧。

hertz我没有尝试是否同样问题，顺便问一下，hertz我看你们官方所说的性能超过fasthttp，这个性能是基于标准库net还是基于netpoll的？

**Comment by li-jin-gou** [comment]
可以看 hertz-benchmark



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年6月3日(周六) 凌晨1:54
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [hertz-contrib/websocket] 压测数据内存占用较高，请帮忙看下压测代码是否可以优化 (Issue #19)




  
websocket 场景使用 hertz 标准库模式就好了。
  
因为是fork gorilla的，测试基于标准库意义不大，直接用gorilla就可以了。
 主要想对比下基于netpoll的是否有性能提升带来质的提高。
 但看上去性能并不比基于标准库强，内存占用却可能比java还吞金兽。
 目前版本对比下来、没什么意义使用基于netpoll的，期待你们以后能优化得更好吧。
 
hertz我没有尝试是否同样问题，顺便问一下，hertz我看你们官方所说的性能超过fasthttp，这个性能是基于标准库net还是基于netpoll的？

**Comment by welkeyever** [comment]
感谢反馈，目前 contrib 库下的 websocket 实现是社区基于 gorilla 适配的，这部分理论上是存在进一步提升的空间的，这部分的优化有相应的规划（不过整体优先级不高）；如果有想法我们也非常欢迎一起探讨，PR is also available🤗

**Comment by lesismal** [comment]
> 如果有想法我们也非常欢迎一起探讨，PR is also available🤗

你们代码的设计模式还是什么太重了，封装的一层又一层的，设计者自己或者团队内做久了熟悉了比较清楚，但是对于外人刚开始读代码太费时间了。

我不知道netty是不是也这种，既然用go了，其实可以写简单点的，至少我是很多次想读一下字节的代码学习一下细节，但每次扫了几分钟一直在调过来跳过去，看一会连个server启动流程都没整明白。
反倒是看标准库的代码，每次都觉得脉络很清晰，顺序下来或者搜一下经常就找到个大概了。

interface 也是只有运行时才知道是在哪里，读代码读到个 interface 还得花好些时间去找到底这里用的是哪个实现

netpoll、kitex、hertz全是这种重设计模式，每次想研究一下，扫几分钟实在就让人看不下去了。

真心建议参考标准库一下，多点大道至简，少整那么多套路和模式

当然，现在已经是这样子了，估计也不会改了，只是吐槽一下。

我自己的 nbio 还有事情可以做，也欢迎来交流、PR。

等你们优化好了也欢迎来更新一波测试用例到我的这个库：
https://github.com/lesismal/go-websocket-benchmark
