### ISSUE TITLE
疑似内存泄漏

### ISSUE THREAD

**Issue by MarsSwimmer** [hertz-contrib/websocket#20]
**Describe the bug**

在上线的项目中，存在websocket的handler中动态创建channel的情况，在使用完成后也手动关闭了channel：close(ch)，在运行一段时间后内存占用增长到了6G，且长时间（3天）不能释放，没有加入websoket handler前，内存占用300mb～500mb。

遂按照示例编写websocket demo，剔除动态创建channel的逻辑，当页面多次刷新后内存占用仍然在增加，随着刷新频率的增加，内存占用也会增长得特别快，且长时间不能释放。

测试过高频访问hertz http handler，不会出现内存增长的情况。

**To Reproduce**

1. 连续快速刷新页面，间隔2秒，再次连续快速刷新页面，不停重复上述操作，能肉眼看到内存增长，大约频繁刷新50次内存增长1MB，且长时间得不到释放。

2. 代码如下：
`func echo(_ context.Context, c *app.RequestContext) {
        defer c.GetConn().Close()
	defer c.Response.SetConnectionClose()
	defer c.Request.SetConnectionClose()
	defer c.Request.CloseBodyStream()
	defer c.Response.CloseBodyStream()

	err := upgrader.Upgrade(c, func(conn *websocket.Conn) {
                defer conn.Close()
		for {
			err = conn.WriteMessage(1, message)
			if err != nil {
				log.Println("write:", err)
				break
			}
		}
	})
	if err != nil {
		log.Print("upgrade:", err)
		return
	}
}
`

**Expected behavior**

1. 请教是否有websocket连接断开后能及时释放内存的方法，希望能指点一二。

**Screenshots**
1. 应用刚启动时内存占用30mb（在项目中）
![截图 2023-10-01 15-19-10](https://github.com/hertz-contrib/websocket/assets/146618222/18a424fc-1ffb-4c46-b06e-cd7bf20c04c4)

2. 频繁刷新、间隔2秒、频繁刷新，重复很多遍后，内存占用40mb，且长时间不释放
![截图 2023-10-01 15-23-39](https://github.com/hertz-contrib/websocket/assets/146618222/6c6a2bee-a765-464d-bf57-e9a12caff26d)

**Hertz version:**

github.com/cloudwego/hertz v0.6.3
github.com/hertz-contrib/cors v0.0.0-20230423034624-2bc83a8400f0
github.com/hertz-contrib/websocket v0.0.1

Please provide the version of Hertz you are using.

**Environment:**
GOVERSION="go1.20"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3838920510=/tmp/go-build -gno-record-gcc-switches"

The output of `go env`.

**Additional context**

**Comment by li-jin-gou** [comment]
pprof 采样火焰图看下 diff 看下内存和 goroutine 增长在哪里。 @swimmingcass

**Comment by li-jin-gou** [comment]
暂时关闭，如果有问题再反馈。 @swimmingcass
