### ISSUE TITLE
hertz websocket segment fault when we used in few months ago 

### ISSUE THREAD

**Issue by xiaofan8421** [hertz-contrib/websocket#21]
**Describe the bug**
It happened that our program crashed because of websocket 's segment-fault  when we used hertz websocket in our ci-test env.

**To Reproduce**
It happened occasionally, with no stable reproduction.

**Expected behavior**
no segment-fault when we use hertz websocket

**Screenshots**
![image](https://github.com/hertz-contrib/websocket/assets/22815750/fc561864-5db6-415a-89e6-d2aecee85690)
From this picture, it seems that happened in the inner side of hertz websokcet implementation.

**Hertz version:**
hertz v0.7.1
Please provide the version of Hertz you are using.

**Environment:**
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/roy/.cache/go-build"
GOENV="/home/roy/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/roy/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/roy/go"
GOPRIVATE=""
GOPROXY="https://goproxy.cn"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.20.6"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/roy/project/go.mod"
GOWORK=""
CGO_CFLAGS="-I /home/roy/kvrocks/build/_deps/rocksdb-src/include"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-L/home/roy/kvrocks/build/_deps/rocksdb-build -L/home/roy/kvrocks/build/_deps/zstd-src/lib -L/home/roy/kvrocks/build/_deps/lz4-src/lib -L/home/roy/kvrocks/build/_deps/snappy-build -lrocksdb -lstdc++ -lm -lz -lsnappy -llz4 -lzstd"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3269662956=/tmp/go-build -gno-record-gcc-switches"
The output of `go env`.

**Additional context**
It seems that no segment-fault when we use the official gorilla/websocket.
I don't know that it is our bad use reason or Hertz Websocket bad implementation.

**Comment by xiaofan8421** [comment]
Maybe websocket connection hijack problem?

**Comment by li-jin-gou** [comment]
- This can be caused by concurrent operations on conn

**Comment by xiaofan8421** [comment]
> * This can be caused by concurrent operations on conn

As I know, gorilla websocket is concurrently accessed safely. Did you mean that hertz hijack websocket conn is not safe for concurrent operation?

**Comment by li-jin-gou** [comment]
> > * This can be caused by concurrent operations on conn
> 
> As I know, gorilla websocket is concurrently accessed safely. Did you mean that hertz hijack websocket conn is not safe for concurrent operation?
yes and maybe you can refer to https://www.cloudwego.io/docs/hertz/tutorials/basic-feature/protocol/websocket/#nohijackconnpool

**Comment by xiaofan8421** [comment]
here "h.NoHijackConnPool = true" in the official hertz doc, this is recommended conf in production to solve this concurrent problem?

**Comment by li-jin-gou** [comment]
> here "h.NoHijackConnPool = true" in the official hertz doc, this is recommended conf in production to solve this concurrent problem?

No,just sending it to you to see.

The error reported here makes me think that the connection has been reclaimed, but the user is still holding a nil conn to write or read the data

**Comment by xiaofan8421** [comment]
> > here "h.NoHijackConnPool = true" in the official hertz doc, this is recommended conf in production to solve this concurrent problem?
> 
> No,just sending it to you to see.
> 
> The error reported here makes me think that the connection has been reclaimed, but the user is still holding a nil conn to write or read the data

Yes, I can't agree more. I know that was illegal memory address access problem a few months ago, but I  didn't have enough time to check the whole code of Hertz's implementation. So I throw our problems into the community If you have any suggestions. For the further discussion, you advise that we use hertz hijacked WS conn with lock?

**Comment by li-jin-gou** [comment]
直接中文了:  你是否可以检查自己的代码中有并发使用或者异步使用？或者尝试提供复现代码，这个问题没有收到过类似的反馈

**Comment by li-jin-gou** [comment]
不需要查看 hertz 的源码，因为同一个 conn 不是并发安全的，这是结论。

**Comment by xiaofan8421** [comment]
BTW, I read your official hertz doc carefully yesterday. I pay attention to this NoHijackConnPool conf, But I think there is little probability about it. 
What I want to say,  are you sure that hertz websocket conn is not concurrent safety? em, ok, I got your answer just now.

**Comment by xiaofan8421** [comment]
对，我们使用中存在对hertz websocket conn的并发访问，在不同的goroutine

**Comment by li-jin-gou** [comment]
> 对，我们使用中存在对hertz websocket conn的并发访问，在不同的goroutine

目前看起来需要加锁

**Comment by xiaofan8421** [comment]
但是我看你们的chat example中貌似也是有在不同goroutine中存在对ws conn的并发访问情形，这个示例也是没有问题的吗？
![image](https://github.com/hertz-contrib/websocket/assets/22815750/ccf81b72-6e35-449a-9f99-8d3e253ba082)

**Comment by li-jin-gou** [comment]
我确定下

**Comment by li-jin-gou** [comment]
@xiaofan8421 Hertz 连接劫持时所使用的hijack conn是池化管理的，因此被劫持的连接在websocket中使用的时候，不支持异步操作（类似将连接传递到协程中这类都是不行的）
 可以先将 h.NoHijackConnPool =true 设置一下，上面的例子中，Upgrade 其实是一直执行，并没有异步。

**Comment by xiaofan8421** [comment]
这里先设置一下的意思是先显示设置一下h.NoHijackConnPool = true ，如果后续还是有，再改用带锁方案？

例子中Upgrade中是一直执行，但它的匿名函数里func(conn  *websocket.Conn){}分别在俩goroutine里执行没有影响吗，我们实际也是类似这样用的，但除了没有显示配NoHijackConnPool，不过chat example中也没配，除了echo那个example

**Comment by xiaofan8421** [comment]
> @xiaofan8421 Hertz 连接劫持时所使用的hijack conn是池化管理的，因此被劫持的连接在websocket中使用的时候，不支持异步操作（类似将连接传递到协程中这类都是不行的） 可以先将 h.NoHijackConnPool =true 设置一下，上面的例子中，Upgrade 其实是一直执行，并没有异步。

@li-jin-gou  这里先设置一下的意思是先显示设置一下h.NoHijackConnPool = true ，如果后续还是有，再改用带锁方案？

例子中Upgrade中是一直执行，但它的匿名函数里func(conn  *websocket.Conn){}分别在俩goroutine里执行没有影响吗，我们实际也是类似这样用的，但除了没有显示配NoHijackConnPool，不过chat example中也没配，除了echo那个example

**Comment by li-jin-gou** [comment]
后续不会有加锁的方案，可以先设置观察一下



---Original---
From: ***@***.***&gt;
Date: Wed, Dec 27, 2023 19:51 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [hertz-contrib/websocket] hertz websocket segment fault when weused in few months ago  (Issue #21)




 
这里先设置一下的意思是先显示设置一下h.NoHijackConnPool = true ，如果后续还是有，再改用带锁方案？
 
例子中Upgrade中是一直执行，但它的匿名函数里func(conn  *websocket.Conn){}分别在俩goroutine里执行没有影响吗，我们实际也是类似这样用的，但除了没有显示配NoHijackConnPool，不过chat example中也没配，除了echo那个example

**Comment by li-jin-gou** [comment]
可以如上先设置观察一下，因为报错看起来并不是并发问题，而是 rc 为 nil ，而能导致 rc 为 nil 的原因看起来是 conn 被回收了。



---Original---
From: ***@***.***&gt;
Date: Wed, Dec 27, 2023 19:52 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [hertz-contrib/websocket] hertz websocket segment fault when weused in few months ago  (Issue #21)




  
@xiaofan8421 Hertz 连接劫持时所使用的hijack conn是池化管理的，因此被劫持的连接在websocket中使用的时候，不支持异步操作（类似将连接传递到协程中这类都是不行的） 可以先将 h.NoHijackConnPool =true 设置一下，上面的例子中，Upgrade 其实是一直执行，并没有异步。
  
@li-jin-gou  这里先设置一下的意思是先显示设置一下h.NoHijackConnPool = true ，如果后续还是有，再改用带锁方案？
 
例子中Upgrade中是一直执行，但它的匿名函数里func(conn  *websocket.Conn){}分别在俩goroutine里执行没有影响吗，我们实际也是类似这样用的，但除了没有显示配NoHijackConnPool，不过chat example中也没配，除了echo那个example

**Comment by xiaofan8421** [comment]
OK，找了下之前Ci测试时记录的case，这是另外多次中的一次断错误截图，貌似也是rc为nil
![image](https://github.com/hertz-contrib/websocket/assets/22815750/dee7158a-6cbd-4c43-aee4-4d5a7c746e1e)

**Comment by xiaofan8421** [comment]
OK，找了下之前Ci测试时记录的case，这是另外多次中的一次断错误截图，貌似也是rc为nil
![image](https://github.com/hertz-contrib/websocket/assets/22815750/9852e307-ab3b-4b1c-9262-1a026e713978)

**Comment by li-jin-gou** [comment]
@xiaofan8421  OK
