### ISSUE TITLE
:sparkles: 似乎没有发挥netpool的优势

### ISSUE THREAD

**Issue by bilinxing** [hertz-contrib/websocket#4]
websocket的绝大多数使用场景特点是单消息体小，收发消息密度高，非常符合netpool的优势。粗略看了下examples，似乎只是照搬了gorilla/websocket，每个连接的读写各需要一个单独的协程，与使用原生net库没有任何区别。是否支持netpool的事件驱动，单个协程处理多个连接的读和写？

**Comment by li-jin-gou** [comment]
hello @bilinxing 
- hertz 的 websocket 扩展是通过 `Hijack` 实现的, 参考
    -  https://github.com/cloudwego/hertz/blob/develop/pkg/app/context.go#L210
    -  https://github.com/hertz-contrib/websocket/blob/main/server.go#L197
- 底层的网络库可以选择 netpoll / 标准库，可以参考 hertz 网络库相关的文档 https://www.cloudwego.io/zh/docs/hertz/tutorials/basic-feature/network-lib/
    -  应用层的 demo 使用两个协程读写 应该和 `是否支持netpool的事件驱动，单个协程处理多个连接的读和写？` 没什么关系，因为底层的网络库可以使用 `netpoll`
